server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_portrait_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 808289
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# CORS配置
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Dify API配置
dify:
  api-key: app-ONZSaUL7v2c9Loa1TVrvf6lu
  base-url: https://api.dify.ai/v1
  dataset-id: dataset-IYnB9skkriUJkdTSCiGkZmuA 